default_platform(:android)

platform :android do
  desc "Build debug APK"
  lane :build do
    gradle(task: "assembleDebug")
  end

  desc "Run unit tests"
  lane :test do
    gradle(task: "testDebugUnitTest")
  end

  desc "Build release APK"
  lane :build_release do
    gradle(task: "assembleRelease")
  end
end
